### ISSUE TITLE
'error': 'Unexpected response from Coze API.'

### ISSUE THREAD

**Issue by AlanceLau** [fatwang2/coze2openai#12]
报错'error': 'Unexpected response from Coze API.'，原来的coze账号token用完了，换了一个账号部署的，报错，这是ip被封杀了吗？

**Comment by fatwang2** [comment]
不是，应该是你的配置问题吗？

AlanceLau ***@***.***>于2024年6月1日 周六21:53写道：

**Comment by AlanceLau** [comment]
是的，我配置错了，应该是发布的时候，没有勾选api

**Comment by AlanceLau** [comment]
谢谢

**Comment by HongYegg** [comment]
我也是这个问题，但是我勾选了api。我是本地部署的，使用的代码测试样例。

**Comment by fatwang2** [comment]
要看下你的配置文件写的对不对，程序是可以正常用的

hongye ***@***.***>于2024年7月9日 周二14:39写道：
