### ISSUE TITLE
你好，Error: The Bot is not currently published to the corresponding platform

### ISSUE THREAD

**Issue by HongYegg** [fatwang2/coze2openai#18]
我检查过，是发布过的bot。我现在很困惑。
PS C:\mozhiwu\coze2openai-main> node .\test.js
{
  error: {
    error: 'Unexpected response from Coze API.',
    message: 'The Bot is not currently published to the corresponding platform\n'
  }
}
PS C:\mozhiwu\coze2openai-main>

**Comment by fatwang2** [comment]
发布的时候勾选 api 了吗

hongye ***@***.***>于2024年7月9日 周二14:37写道：

**Comment by HongYegg** [comment]
谢谢，我勾选了。最终原因时把com改为cn

**Comment by fatwang2** [comment]
哦哦，国内和国外是两个地址，部署的时候需要注意

hongye ***@***.***>于2024年7月11日 周四09:07写道：
