### ISSUE TITLE
如何在客户端切换模型

### ISSUE THREAD

**Issue by guo-zh** [fatwang2/coze2openai#20]
我已经在.env中配置了多个coze中的bot，想知道如何能在客户端切换bot，或者说能通过什么触发词来使用其他bot

**Comment by fatwang2** [comment]
模型呀

guo-zh ***@***.***>于2024年8月1日 周四14:32写道：

**Comment by guo-zh** [comment]
我在聊天界面是触发不了的对吗？

**Comment by fatwang2** [comment]
在你的聊天程序里，如果可以切换模型，不就可以了

guo-zh ***@***.***>于2024年8月1日 周四15:34写道：
