### ISSUE TITLE
大佬有兴趣开发poe api转换吗

### ISSUE THREAD

**Issue by TeamFan** [fatwang2/coze2openai#5]
https://github.com/Timmy-web/Poe-Telegram-Chatbot 这个项目把api用在了tg bot上，不支持图片文档这些，大佬有兴趣把开发转换为oai格式吗😂

**Comment by fatwang2** [comment]
我不做逆向哈，我这个项目只是做 API 之间的格式转发，Poe没有开放 API，我不做的

**Comment by TeamFan** [comment]
你好，它是仅面向Poe订阅用户开放的api，不是逆向。申请地址是https://poe.com/api_key 
这是poe官方的介绍https://creator.poe.com/docs/accessing-other-bots-on-poe#how-to-access-the-bot-query-api-directly

**Comment by TeamFan** [comment]
https://poe.com/api_key这个功能仅面向订阅用户开放，不是逆向。

**Comment by fatwang2** [comment]
这个是开发 poe 机器人的，不是对外的

**Comment by TeamFan** [comment]
不是啊，这个是直接通过api来调用poe的bot的，本质上还是直接调用它的模型，可以面向订阅用户自己使用啊
![image](https://github.com/fatwang2/coze2openai/assets/129395999/18f6d4ec-981f-4ab6-aade-3ea604827979)
这个是利用上面那个开源项目，调用这个api来使用他的bot的一个示例
![image](https://github.com/fatwang2/coze2openai/assets/129395999/1a09d2fe-ccc9-4c47-80fb-d68ae6fc2d90)

**Comment by fatwang2** [comment]
调用之后，开发自定义 poe 机器人的

LUO Xiangyu ***@***.***>于2024年4月17日 周三19:44写道：

**Comment by TeamFan** [comment]
技术文档里面，我没有理解错误的话，是通过api调用，但是并不能修改模型和开发，他能提供这个api调用在poe上公开的所有模型，包括poe官方提供的和第三方作者制作的。但是与自己利用api去开发调整模型好像没什么关系。如果有错误，麻烦您指正！如果实在是麻烦到您呢，非常抱歉！

**Comment by fatwang2** [comment]
我之前开发过，你可以调用 Poe 上的模型开发自己的 Poe 机器人，但是不能直接把接口对外服务，我看接口文档还是原来那个，应该没变

LUO Xiangyu ***@***.***>于2024年4月17日 周三19:53写道：

**Comment by TeamFan** [comment]
抱歉，直接接到tg上使用算对外服务吗？因为上面那个开源项目就是订阅用户自己申请自己的api，调用poe的模型直接获取回答。

**Comment by fatwang2** [comment]
我研究研究tg那个项目吧，别激动。。。

**Comment by TeamFan** [comment]
没有没有，我没有激动，我可能语气上有点问题，如果感到冒犯，非常抱歉。我上一条只是单纯问一下tg调用算不算对外😂因为我自己调用着玩了好长一段时间了，自己又只是个小白，所以问一下，没有别的意思

**Comment by fatwang2** [comment]
这个是官方文档对于server bots的规划，他们是希望最终机器人还是在Poe里使用

![image](https://github.com/fatwang2/coze2openai/assets/134143178/3e60f14a-ed1e-40e9-9769-e4c9df575c5d)

但同时他们也提供了API访问该机器人的辅助能力用来做测试，也就是telegram函数调用的这个

![CleanShot 2024-04-20 at 01 45 06@2x](https://github.com/fatwang2/coze2openai/assets/134143178/f953808c-79ac-45ae-9e87-aaeadfe47de1)

我理解这不是一个官方推荐在生产环境日常使用的方式，可能是速度也不快，毕竟要多走几道，但确实不是逆向的方案。我找了一个好像能解决这个问题的项目，你有订阅吗？可以试试看 https://github.com/snssll/poe2openai

**Comment by TeamFan** [comment]
有的，谢谢！大佬需要测试的话，我可以提供api！我之前找过一下，但是没有找到这个项目，非常感谢！

**Comment by fatwang2** [comment]
你先试试这个项目，看看是不是满足，满足我就不重复造轮子了

LUO Xiangyu ***@***.***>于2024年4月20日 周六17:39写道：

**Comment by TeamFan** [comment]
应该没什么问题，谢谢大佬！
