### ISSUE TITLE
本人小白，其他能看懂，用法里的那段代码怎么用

### ISSUE THREAD

**Issue by ainp** [fatwang2/coze2openai#7]
本人小白，其他能看懂，用法里的那段代码怎么用

**Comment by fatwang2** [comment]
就是你把部署后的链接，放在支持 OpenAI 的客户端里就可以用

ainp ***@***.***>于2024年4月24日 周三12:24写道：

**Comment by fatwang2** [comment]
你如果是有OpenAI的三方客户端的话，直接用就行，我更新了说明文档，加了截图

**Comment by ainp** [comment]
多谢了
