### ISSUE TITLE
适配openai 格式的 message  type =  system 

### ISSUE THREAD

**Issue by jiahut** [fatwang2/coze2openai#9]
coze的 message 不支持  "system" 类型的消息 (prompt)

openai 的客户端设置的 prompt (即 system 类型的消息 ) 不能正确的传递

参考
https://www.coze.com/docs/developer_guides/chat?_lang=zh
![image](https://github.com/fatwang2/coze2openai/assets/1067691/ec0bca51-bd5a-4d60-b8cf-26f6f41cb5fc)

**Comment by fatwang2** [comment]
什么意思

**Comment by nice70** [comment]
参考我的app.js修改一下就好了，接收请求，以及格式化coze响应的时候处理一下https://github.com/nice70/coze2openai/blob/main/app.js
